"""initial_schema

Revision ID: 3c81049921f5
Revises: 
Create Date: 2026-04-14 12:22:44.622700

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3c81049921f5'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Activer l'extension pg_trgm pour la recherche floue (GIN indexes)
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pseudo', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pseudo')
    )
    op.create_table('agenda_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titre', sa.String(length=200), nullable=False),
    sa.Column('date_debut', sa.Date(), nullable=False),
    sa.Column('date_fin', sa.Date(), nullable=False),
    sa.Column('lieu', sa.String(length=200), nullable=True),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('lien_externe', sa.String(length=500), nullable=True),
    sa.Column('locked_by', sa.Integer(), nullable=True),
    sa.Column('locked_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint('date_fin >= date_debut', name='chk_dates'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['locked_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('articles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titre', sa.String(length=200), nullable=False),
    sa.Column('description', sa.String(length=300), nullable=True),
    sa.Column('image_ref', sa.String(length=500), nullable=True),
    sa.Column('source_url', sa.String(length=500), nullable=True),
    sa.Column('date_publication', sa.Date(), nullable=False),
    sa.Column('auteur', sa.String(length=100), nullable=True),
    sa.Column('categorie', sa.String(length=100), nullable=True),
    sa.Column('locked_by', sa.Integer(), nullable=True),
    sa.Column('locked_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint("categorie IN ('Langue & Culture', 'Littérature', 'Poésie', 'Histoire & Mémoire', 'Traditions & Fêtes', 'Musique', 'Danse', 'Gastronomie', 'Artisanat', 'Patrimoine bâti', 'Environnement', 'Personnalités', 'Associations', 'Enseignement', 'Économie locale', 'Numismatique & Archives', 'Immigration & Diaspora', 'Jeunesse', 'Régionalisme & Politique linguistique', 'Divers')", name='chk_categorie'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['locked_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dict_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mot_fr', sa.String(length=200), nullable=False),
    sa.Column('synonyme_fr', sa.String(length=200), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('theme', sa.String(length=100), nullable=True),
    sa.Column('categorie', sa.String(length=100), nullable=True),
    sa.Column('locked_by', sa.Integer(), nullable=True),
    sa.Column('locked_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['locked_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_dict_entries_mot_fr_trgm', 'dict_entries', ['mot_fr'], unique=False, postgresql_using='gin', postgresql_ops={'mot_fr': 'gin_trgm_ops'})
    op.create_table('edit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('table_name', sa.String(length=50), nullable=False),
    sa.Column('row_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=10), nullable=False),
    sa.Column('old_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('new_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('done_by', sa.Integer(), nullable=True),
    sa.Column('done_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint("action IN ('INSERT', 'UPDATE', 'DELETE')", name='chk_action'),
    sa.ForeignKeyConstraint(['done_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_edit_log_table_row', 'edit_log', ['table_name', 'row_id', 'done_at'], unique=False)
    op.create_table('library_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titre', sa.String(length=200), nullable=False),
    sa.Column('typologie', sa.String(length=20), nullable=True),
    sa.Column('periode', sa.String(length=200), nullable=True),
    sa.Column('description_courte', sa.String(length=200), nullable=True),
    sa.Column('description_longue', sa.Text(), nullable=True),
    sa.Column('source_url', sa.String(length=500), nullable=True),
    sa.Column('image_ref', sa.String(length=500), nullable=True),
    sa.Column('lang', sa.CHAR(length=2), server_default='fr', nullable=True),
    sa.Column('traduction_id', sa.Integer(), nullable=True),
    sa.Column('locked_by', sa.Integer(), nullable=True),
    sa.Column('locked_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint("typologie IN ('Histoire', 'Légende')", name='chk_typologie'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['locked_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['traduction_id'], ['library_entries.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sayings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('terme_provencal', sa.Text(), nullable=False),
    sa.Column('localite_origine', sa.String(length=200), nullable=False),
    sa.Column('traduction_sens_fr', sa.Text(), nullable=False),
    sa.Column('type', sa.String(length=30), nullable=True),
    sa.Column('contexte', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=300), nullable=True),
    sa.Column('locked_by', sa.Integer(), nullable=True),
    sa.Column('locked_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint("type IN ('Dicton', 'Expression', 'Proverbe')", name='chk_type'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['locked_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_sayings_terme_trgm', 'sayings', ['terme_provencal'], unique=False, postgresql_using='gin', postgresql_ops={'terme_provencal': 'gin_trgm_ops'})
    op.create_table('dict_translations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entry_id', sa.Integer(), nullable=False),
    sa.Column('graphie', sa.String(length=50), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=True),
    sa.Column('traduction', sa.String(length=500), nullable=False),
    sa.Column('region', sa.String(length=50), nullable=True),
    sa.Column('locked_by', sa.Integer(), nullable=True),
    sa.Column('locked_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['entry_id'], ['dict_entries.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['locked_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_dict_translations_trgm', 'dict_translations', ['traduction'], unique=False, postgresql_using='gin', postgresql_ops={'traduction': 'gin_trgm_ops'})
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_dict_translations_trgm', table_name='dict_translations', postgresql_using='gin', postgresql_ops={'traduction': 'gin_trgm_ops'})
    op.drop_table('dict_translations')
    op.drop_index('idx_sayings_terme_trgm', table_name='sayings', postgresql_using='gin', postgresql_ops={'terme_provencal': 'gin_trgm_ops'})
    op.drop_table('sayings')
    op.drop_table('library_entries')
    op.drop_index('idx_edit_log_table_row', table_name='edit_log')
    op.drop_table('edit_log')
    op.drop_index('idx_dict_entries_mot_fr_trgm', table_name='dict_entries', postgresql_using='gin', postgresql_ops={'mot_fr': 'gin_trgm_ops'})
    op.drop_table('dict_entries')
    op.drop_table('articles')
    op.drop_table('agenda_events')
    op.drop_table('users')
    op.execute("DROP EXTENSION IF EXISTS pg_trgm")
    # ### end Alembic commands ###
